### ISSUE TITLE
bolt-boltforms.yml config vars aren't read correctly

### ISSUE THREAD

**Issue by iamgoodbytes** [bobdenotter/forms#19]
**bolt 4.1 + bolt/forms**

When submitting a form it will crash with the error: `An exception has been thrown during the rendering of a template ("Notice: Trying to access array offset on value of type null").`

When dumping  the config var in `vendor/bolt/forms/src/factory/EmailFactory.php` at line 29 like so
```
dd($config->get('debug'));
$debug = (bool) $config->get('debug')['enabled']; 
```
an error is triggered because the config is null

<img width="386" alt="Screenshot 2020-10-16 at 13 26 07" src="https://user-images.githubusercontent.com/3899360/96253019-26d52e80-0fb3-11eb-913e-2f21d0c8f0f1.png">

**Comment by I-Valchev** [comment]
hi @iamgoodbytes , like I mentioned on Slack I wasn't able to reproduce this yet.

Do you have the following lines in your `config/extensions/bolt-boltforms.yaml`?

```
## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.
debug:
    enabled: false
    address: ivo@example.org
```

**Comment by LordSimal** [comment]
I would also like to see if the `config/extensions/bolt-boltforms.yaml` is present at that location with the given data

**Comment by iamgoodbytes** [comment]
@LordSimal yes I do have that file at the exact location.

```
## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.
debug:
    enabled: true
    address: noreply@example.com
```

If it helps: changing debug:enabled to true or false has effect on my contact form, so it's being read. Only when submitting the form it crashes with the error above. 

Do you have PHP 7.4? Because that seems to be one of the factors that triggers this.

**Comment by iamgoodbytes** [comment]
<img width="316" alt="Screenshot 2020-10-16 at 16 27 10" src="https://user-images.githubusercontent.com/3899360/96270849-7116d980-0fcc-11eb-851c-3026f4ad2b0d.png">

**Comment by iamgoodbytes** [comment]
And another update: when testing with the default "contact" form, the same error happens.

**Comment by LordSimal** [comment]
I know there is some way to "overwrite" the config with specificly placed yaml files in your theme.
I guess you don't have yaml files in your theme, do you?

**Comment by iamgoodbytes** [comment]
I don't. Should I have them there and is this documented?

**Comment by iamgoodbytes** [comment]
Also: can you confirm you tested on php 7.4 when you say you couldn't reproduce the error above?

**Comment by LordSimal** [comment]
I now tried that with PHP 7.4 as well and can confirm, that I have the same problem.

## What I did

- installed bolt/forms ^0.4.3
- added my MAILER_DSN in the .env file
- added `{{ boltform('contact') }}` to the `public/theme/base-2021/partials/_master.twig` before the footer is included
- tried to send the form

And then basically got the same error as described above.
I am running on PHP 7.4.11

This is basically a "bare" BoltCMS install with demo data which has been upgraded from 4.0 to 4.1.1 recently.

**Comment by LordSimal** [comment]
I don't know if thats correct, but is this Class correct for the `$config` variable?
![image](https://user-images.githubusercontent.com/9105243/96366213-68e2a980-1146-11eb-8d96-0e4e58ee0427.png)

I used the `Bolt\Configuration\Config` for accessing the Config.

**Comment by iamgoodbytes** [comment]
My knowledge of bolt is limited, but when I look at the other files that use $config I can see that they reference `use Bolt\Configuration\Config;` instead.

**Comment by LordSimal** [comment]
I just tried what I said above but this doesn't work, because the MailFactory is being created by `src/EventSubscriber/Mailer.php` on line 68 where the given `$this->event->getFormConfig()` is definitely not a Bolt Config object.

**Comment by LordSimal** [comment]
Ok I get what its trying to do.
Basically the `debug` value which can't be parsed to in this PHP File can be set per configured form.
I was misunderstand that as the "global" debug config for this.

But now the problem is why is the given Collection not the config from the bolt-boltforms.yaml.

Digging deeper...

**Comment by LordSimal** [comment]
The problem is, that `$config` here is the "correct" config for this current form set in the `bolt-boltforms.yaml`... BUT
the logic in PHP `src/Factory/EmailFactory.php` depends on variables in specific positions in that .yaml file like
```
$config->get('debug')['enabled']
```

Expect that you got something like that
```
## Example 1
#
# Contact Form
contact:
    debug:                    <--------------------
        enabled: true     <--------------------
    notification:
        ....
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fields:
        ....
```

Which is definitely not present in the default installed `bolt-boltforms.yaml` because they are part of the `notification` "array"

I will try to get an PR for that ready to fix this.

@I-Valchev any comments on that?

**Comment by LordSimal** [comment]
nope, I misunderstood that wrong again.

Basically the "general" debug config isn't present in the `src/Factory/EmailFactory.php`

I mean this part at the start of `bolt-boltforms.yaml`

```
## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.
debug:
    enabled: true
    address: noreply@example.com
```

The problem here is, that the `src/EventSubscriber/Mailer.php` only parses the FormConfig to the MailFactory, not the whole config (or just the debug config for example)
